apiVersion: v1
kind: Pod
metadata:
  name: nginx-data-1
spec:
  containers:
    - name: nginx-data-1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name:  nginx-data-1
  volumes:
    - name: nginx-data-1
      persistentVolumeClaim:
        claimName: nfs-data-1-pvc